import React, { useState } from 'react';
import { db } from './firebase'; // Ensure this points to your firebase.js file
import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import { PlusCircle, Building2, User, MapPin, CheckCircle2, Loader2 } from 'lucide-react';

export default function CreateProject() {
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [formData, setFormData] = useState({
    projectName: '',
    customerName: '',
    projectCity: '',
    projectAddress: '',
    customerCity: '',
    customerAddress: ''
  });

  // Function to generate a random 10-digit Project ID
  const generateID = () => {
    return Math.floor(1000000000 + Math.random() * 9000000000).toString();
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setSuccess(false);

    const autoGeneratedID = generateID();

    try {
      // 1. Reference the 'projects' collection in Firestore
      const docRef = await addDoc(collection(db, "projects"), {
        ...formData,
        projectId: autoGeneratedID,
        createdAt: serverTimestamp(), // Uses Firebase server time
        status: 'Active',
        progress: 0
      });

      console.log("Document written with ID: ", docRef.id);
      
      // 2. Show success state
      setSuccess(true);
      
      // 3. Reset form after 2 seconds
      setTimeout(() => {
        setFormData({
          projectName: '',
          customerName: '',
          projectCity: '',
          projectAddress: '',
          customerCity: '',
          customerAddress: ''
        });
        setSuccess(false);
      }, 3000);

    } catch (error) {
      console.error("Error adding document: ", error);
      alert("Error saving project: " + error.message);
    } finally {
      setLoading(false);
    }
  };

  const inputStyle = {
    width: '100%',
    padding: '12px',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '14px',
    marginBottom: '5px',
    outline: 'none',
    boxSizing: 'border-box'
  };

  const labelStyle = {
    display: 'block',
    marginBottom: '5px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: '#666',
    textTransform: 'uppercase'
  };

  return (
    <div style={{ maxWidth: '700px', margin: '40px auto', padding: '30px', background: '#fff', borderRadius: '16px', boxShadow: '0 10px 25px rgba(0,0,0,0.05)' }}>
      <div style={{ textAlign: 'center', marginBottom: '30px' }}>
        <h2 style={{ margin: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', color: '#1a1a1a' }}>
          <PlusCircle size={28} /> Create New Interior Project
        </h2>
        <p style={{ color: '#666', marginTop: '8px' }}>Enter project details to initialize the management workflow</p>
      </div>

      {success && (
        <div style={{ backgroundColor: '#ecfdf5', color: '#059669', padding: '15px', borderRadius: '8px', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '10px', fontWeight: '500' }}>
          <CheckCircle2 size={20} /> Project successfully saved to the database!
        </div>
      )}

      <form onSubmit={handleSubmit}>
        {/* --- SECTION 1: CORE DETAILS --- */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '20px' }}>
          <div>
            <label style={labelStyle}><Building2 size={12} /> Project Name</label>
            <input required placeholder="e.g. Skyline Apartment" value={formData.projectName} onChange={(e) => setFormData({...formData, projectName: e.target.value})} style={inputStyle} />
          </div>
          <div>
            <label style={labelStyle}><User size={12} /> Customer Name</label>
            <input required placeholder="e.g. John Doe" value={formData.customerName} onChange={(e) => setFormData({...formData, customerName: e.target.value})} style={inputStyle} />
          </div>
        </div>

        {/* --- SECTION 2: LOCATION DETAILS --- */}
        <div style={{ borderTop: '1px solid #eee', paddingTop: '20px', marginBottom: '20px' }}>
          <h4 style={{ margin: '0 0 15px 0', fontSize: '14px', color: '#333' }}>Location Information</h4>
          
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '15px' }}>
            <div>
              <label style={labelStyle}>Project City</label>
              <input required placeholder="City where work happens" value={formData.projectCity} onChange={(e) => setFormData({...formData, projectCity: e.target.value})} style={inputStyle} />
            </div>
            <div>
              <label style={labelStyle}>Customer City</label>
              <input required placeholder="Customer's current city" value={formData.customerCity} onChange={(e) => setFormData({...formData, customerCity: e.target.value})} style={inputStyle} />
            </div>
          </div>

          <div style={{ marginBottom: '15px' }}>
            <label style={labelStyle}>Project Full Address</label>
            <textarea rows="2" placeholder="Site address..." value={formData.projectAddress} onChange={(e) => setFormData({...formData, projectAddress: e.target.value})} style={inputStyle} />
          </div>

          <div>
            <label style={labelStyle}>Customer Billing Address</label>
            <textarea rows="2" placeholder="Billing address..." value={formData.customerAddress} onChange={(e) => setFormData({...formData, customerAddress: e.target.value})} style={inputStyle} />
          </div>
        </div>

        {/* --- SUBMIT BUTTON --- */}
        <button 
          type="submit" 
          disabled={loading}
          style={{ 
            width: '100%', 
            padding: '14px', 
            background: loading ? '#666' : '#000', 
            color: '#fff', 
            border: 'none', 
            borderRadius: '8px', 
            cursor: loading ? 'not-allowed' : 'pointer', 
            fontWeight: 'bold',
            fontSize: '16px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '10px',
            transition: 'background 0.3s'
          }}
        >
          {loading ? (
            <><Loader2 className="animate-spin" size={20} /> Connecting to Firestore...</>
          ) : (
            'Initialize Project'
          )}
        </button>
      </form>
    </div>
  );
}